#define TAM_BLOCO 4096
#define BLOCO_REGISTROS 7
#define BUCKETS 15000
#define BLOCOS 15
#define ALTURA_ARVORE_PRIMARIA 5
#define ALTURA_ARVORE_SECUNDARIA 5
#define ARQUIVO_HASHTABLE "hashtable_dados.bin"
#define ARQUIVO_ARVORE_PRIMARIA "arvore_primaria_dados.bin"
#define ARQUIVO_ARVORE_SECUNDARIA "arvore_secundaria_dados.bin"